### ISSUE TITLE
Cuteness Phonology Rules - Nasal 'm' #!Phonology

### ISSUE THREAD

**Issue by CxpcakeTheDerp** [ArztVielfrass/VendictMarkdown#19]
Issues:

Does Nasal 'M' really sound cute?
There are some combinations to make it sound cute.
Example:
Miu  // Female sounding name I guess
Mui // Mu-ee? Mooi doesn't sound cute though.
Myu // Another -yu suffix sound

**Comment by ArztVielfrass** [comment]
It can be if you only use 2 morae, except it doesn't if you only use 1 morae, maybe add it in with a special case of rule:
Nasal Bilabial M must have a 2 morae sound.
This is also the case for 'ch' dithong.

**Comment by CxpcakeTheDerp** [comment]
Gute idea.

**Comment by ArztVielfrass** [comment]
You can play around with suprasegmentals, the sounds themselves isn't what makes them cute, but: rhythm, intonotation, vowel reduction, pitch and sound all contribute. See VendictMD/Phonology/Supgrasegmentals
