### ISSUE TITLE
"IME" Vendict

### ISSUE THREAD

**Issue by ArztVielfrass** [ArztVielfrass/VendictMarkdown#27]
Instead of typing in Vendict 100%, type in English and that gets translated to Vendict.
No special things... only a word to word translator, does not understand context

**Comment by CxpcakeTheDerp** [comment]
This is not an IME, but rather, a full blown translator.
On the other hand, I am building a keyboard layout for Vendict.
Please provide a full list.
https://github.com/ArztVielfrass/VendictMarkdown/blob/master/Phonology/Phonotactics.md??
Is this complete?

**Comment by ArztVielfrass** [comment]
Still an IME, it can't translate

**Comment by ArztVielfrass** [comment]
See, VendictMD/IME

**Comment by CxpcakeTheDerp** [comment]
An AHK script? Hmm, a pretty good hack-in solution.

**Comment by ArztVielfrass** [comment]
I can't program, ahk is the only good thing I know

**Comment by CxpcakeTheDerp** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/dd318170(v=vs.85).aspx

I could write some C++ code or C# code with .NET Framework, and some knowledge on the Windows API.

It would take some time to develop this such system.

**Comment by CxpcakeTheDerp** [comment]
frick u i just copy paste p/invokes okay :c
