### ISSUE TITLE
Lexicon Extractor

### ISSUE THREAD

**Issue by ArztVielfrass** [ArztVielfrass/VendictMarkdown#28]
Input text -> Adds words to .TSV
Input text -> Adds words that is non existant in the previous .TSV file

**Comment by CxpcakeTheDerp** [comment]
Please provide more information.

**Comment by ArztVielfrass** [comment]
Example:
Input text: "Wo et mes soul" -> .CSV
Add lines to CSV: "wo, et, mes, soul"

Input text: "wo et mes harth" -> .CSV
CSV now is: "wo, et, mes, soul, harth"
Notice that words already in the CSV isn't added
Importance: Very Low

**Comment by CxpcakeTheDerp** [comment]
Finished. Now it needs testing. #33 Need to generate unit tests.
