### ISSUE TITLE
Vendict Syllables 

### ISSUE THREAD

**Issue by CxpcakeTheDerp** [ArztVielfrass/VendictMarkdown#29]
http://english.glendale.cc.ca.us/phonics.rules.html

Looking at the sample sentences, one cannot know where one sound should stop. Or whatever you call this in phonology.

**Comment by CxpcakeTheDerp** [comment]
https://github.com/ArztVielfrass/VendictMarkdown/blob/master/Phonology/Phonotactics.md
Was just reading this..

**Comment by ArztVielfrass** [comment]
Don't worry about it
