### ISSUE TITLE
Vendict Keyboard Layout

### ISSUE THREAD

**Issue by CxpcakeTheDerp** [ArztVielfrass/VendictMarkdown#35]
https://unicode-table.com/en/

Please send the finalized character set. I will be looking around the unicode table to find suitable characters

We can only find characters in ranges 0000-FFFF
Because UTF32 sucks

**Comment by ArztVielfrass** [comment]
Characters won't properly display in Git

**Comment by ArztVielfrass** [comment]
ABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz

0123456789

~!@#$%^&*()_+`-=

{}[];:'"\|,<.?※¶◊÷×«»‽

Special Characters:
ā Ā
â Â
ø Ø

Ligatures:
ʒ

dʒ lʒ tʒ
